import "./globals.css";

import { AppWrapper } from "./providers/AppProvider";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { NextAuthProvider } from "./providers/SessionWrapper";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
